language: python
python:
- '3.6'
sudo: required
before_install:
  - "sudo apt-get install pandoc"
  - "pandoc --from=markdown --to=rst --output=README README.md"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install pycodestyle"
script:
  - pycodestyle
deploy:
- provider: pypi
  skip_cleanup: true
  distributions: "sdist"
  user: BlackSmith
  password:
    secure: ES8mpWwlZ8QchOgSwJhjdOrSY0BcG5hWWJ+1us7jy5jxuCbZazHP6AvUkTAamaZGrcIUdlJ/eDK3XjRfGNwhHkUyZEbBZshXBvpFmFgCK5yu7f+JV3c1oHBMBgF+FR5j5zOsu/yCGrQ5hEBZ1G1l6Mcp665qc5WZxJGIzzGkQ/0erfOdIhcR6n8wMIUDes7z9rKvEJNGkKSM7P8e3JPmzf8JHFMScYsj5TixkM4XAxp7vSefobUtzhVv/i6eBAPCRW996kIWu/kLHxQgQp4z3YIlnrDPWM8DY13TnNJD6BIF3bPb0I3wp/wP8yKB3tjvD9fn0JOGFC6gUv8yU2SK0oHs4TwRMdRuSc5/c1jxzyyYFNMNsS8xFh6tC8GmLGNKPHvyuZ10hAX0nWvpJmxCVV/JPYNCsAqgHympGRVY6MXuUvUlNeIwLXJuNiqEhuJXKkkWbYQ0lNJed5x7tgDfUrCjk5P7UTfiaJKcNW40Ow5hz7wDkD/cwlYOhHXAK8ebdrQv872f+G4Tn4/Gbv2yQR+jxQYtAiYPDnnW/2EZLQnttzivi7SJaQbr8pDGueBvBroxq4DRJFGH8zb8zfOuIvmV8CZf7UqsuDtlYyUW9kB4nEppGnhcRSK3Hs5m620j0tR//V0+Tw4lHOGeD+FlgK04T6horuhPQUihWJpZG5A=
  on:
    tags: true
    all_branches: true
#    condition: $TRAVIS_PYTHON_VERSION = 3.6
#    branch: master    
