language: python
python:
- '3.6'
sudo: required
before_install:
  - "sudo apt-get install pandoc"
  - "pandoc --from=markdown --to=rst --output=README README.md"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install pycodestyle"
script:
  - pycodestyle
deploy:
- provider: pypi
  skip_cleanup: true
  distributions: "sdist"
  user: ogajduse
  password:
    secure: "SS0wP9IvYXxmY+1zKxcgMWJOWloYkp944kenVmjKkRwdUWdRlVQ+phy51tkHoczrDyDEvxL897heJkrP1xbUYS0h1viFMFsOj2Fh0CWDcyZecHDoQje8J42fmwDp70OgN5LJfw57rGR2HuqzF37O9ws2C1qwCF05TfF0kB2xw2C8ap5E5xPy2Wq9yU9nSaq/RsU77i2AMdqe0M9ESFvxP4+E2iIDGpnuHymGqdKt2jghZMnfBxWlKxJGMIN15OT8PMnP7+UxR1198dSW1h7p1gAtjx3phczwyTj2H+/uzVxAGnAfdzvZBhwikDVY3tw/5x66jdwB4Bpxtc+D4MKy/ytzyEOGe59uS/Zii3cgKXtft0QIEcEp6DY2Vh1LL0gzrhP7eZhMIS/ESyX64YXZJnlOk2DpNZlc3ZFs11ihpBKvHzxPC2/m4z20wjGho91NF+96FQQ3FIqmqHgxViV11E8Cu3LeltPDmxBLrkReIAjPtdh0on9AMQqq4HSNVbEZmmsfOho99TVL+NH8poeGNB9HNS3D/T9OFxqYYRh3c8MuQW1h4M6Ef+IIyKFlPjWygaD59uoirVoZ62YrSJuBrcdiciKQBQ9DtmtQeqMMDAPUvR2PjYwj9/OlIzImRP8cVMoV+1jVXbFZGcKqu6ENtBDv1ZxKuOwJ/T/MnycnPaM="
  on:
    tags: true
    all_branches: true
#    condition: $TRAVIS_PYTHON_VERSION = 3.6
#    branch: master    
